=begin
#スマレジ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module OpenapiClient
  # POS APIの型表現にバグと思われる矛盾があるため、CustomersResponseを流用できない
  class CustomersResponseOfCreate
    attr_accessor :customer_id

    attr_accessor :customer_code

    attr_accessor :customer_no

    attr_accessor :rank

    attr_accessor :staff_rank

    attr_accessor :first_name

    attr_accessor :last_name

    attr_accessor :first_kana

    attr_accessor :last_kana

    attr_accessor :post_code

    attr_accessor :address

    attr_accessor :phone_number

    attr_accessor :fax_number

    attr_accessor :mobile_number

    attr_accessor :mail_address

    attr_accessor :mail_address2

    attr_accessor :mail_address3

    attr_accessor :company_name

    attr_accessor :department_name

    attr_accessor :managerial_position

    attr_accessor :sex

    attr_accessor :birth_date

    attr_accessor :point_expire_date

    attr_accessor :last_come_date_time

    attr_accessor :entry_date

    attr_accessor :leave_date

    attr_accessor :point_giving_unit_price

    attr_accessor :point_giving_unit

    attr_accessor :pin_code

    attr_accessor :passport_no

    attr_accessor :nationality

    attr_accessor :alphabet_name

    attr_accessor :mail_receive_flag

    attr_accessor :note

    attr_accessor :note2

    attr_accessor :favorite_list

    attr_accessor :browsing_list

    attr_accessor :status

    attr_accessor :store_id

    attr_accessor :ins_date_time

    attr_accessor :upd_date_time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'customer_id' => :'customerId',
        :'customer_code' => :'customerCode',
        :'customer_no' => :'customerNo',
        :'rank' => :'rank',
        :'staff_rank' => :'staffRank',
        :'first_name' => :'firstName',
        :'last_name' => :'lastName',
        :'first_kana' => :'firstKana',
        :'last_kana' => :'lastKana',
        :'post_code' => :'postCode',
        :'address' => :'address',
        :'phone_number' => :'phoneNumber',
        :'fax_number' => :'faxNumber',
        :'mobile_number' => :'mobileNumber',
        :'mail_address' => :'mailAddress',
        :'mail_address2' => :'mailAddress2',
        :'mail_address3' => :'mailAddress3',
        :'company_name' => :'companyName',
        :'department_name' => :'departmentName',
        :'managerial_position' => :'managerialPosition',
        :'sex' => :'sex',
        :'birth_date' => :'birthDate',
        :'point_expire_date' => :'pointExpireDate',
        :'last_come_date_time' => :'lastComeDateTime',
        :'entry_date' => :'entryDate',
        :'leave_date' => :'leaveDate',
        :'point_giving_unit_price' => :'pointGivingUnitPrice',
        :'point_giving_unit' => :'pointGivingUnit',
        :'pin_code' => :'pinCode',
        :'passport_no' => :'passportNo',
        :'nationality' => :'nationality',
        :'alphabet_name' => :'alphabetName',
        :'mail_receive_flag' => :'mailReceiveFlag',
        :'note' => :'note',
        :'note2' => :'note2',
        :'favorite_list' => :'favoriteList',
        :'browsing_list' => :'browsingList',
        :'status' => :'status',
        :'store_id' => :'storeId',
        :'ins_date_time' => :'insDateTime',
        :'upd_date_time' => :'updDateTime'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'customer_id' => :'Object',
        :'customer_code' => :'String',
        :'customer_no' => :'String',
        :'rank' => :'String',
        :'staff_rank' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'first_kana' => :'String',
        :'last_kana' => :'String',
        :'post_code' => :'String',
        :'address' => :'String',
        :'phone_number' => :'String',
        :'fax_number' => :'String',
        :'mobile_number' => :'String',
        :'mail_address' => :'String',
        :'mail_address2' => :'String',
        :'mail_address3' => :'String',
        :'company_name' => :'String',
        :'department_name' => :'String',
        :'managerial_position' => :'String',
        :'sex' => :'Sex',
        :'birth_date' => :'String',
        :'point_expire_date' => :'String',
        :'last_come_date_time' => :'String',
        :'entry_date' => :'String',
        :'leave_date' => :'String',
        :'point_giving_unit_price' => :'String',
        :'point_giving_unit' => :'String',
        :'pin_code' => :'String',
        :'passport_no' => :'String',
        :'nationality' => :'String',
        :'alphabet_name' => :'String',
        :'mail_receive_flag' => :'MailReceiveFlag',
        :'note' => :'String',
        :'note2' => :'String',
        :'favorite_list' => :'String',
        :'browsing_list' => :'String',
        :'status' => :'Status',
        :'store_id' => :'String',
        :'ins_date_time' => :'String',
        :'upd_date_time' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::CustomersResponseOfCreate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::CustomersResponseOfCreate`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'customer_code')
        self.customer_code = attributes[:'customer_code']
      end

      if attributes.key?(:'customer_no')
        self.customer_no = attributes[:'customer_no']
      end

      if attributes.key?(:'rank')
        self.rank = attributes[:'rank']
      end

      if attributes.key?(:'staff_rank')
        self.staff_rank = attributes[:'staff_rank']
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'first_kana')
        self.first_kana = attributes[:'first_kana']
      end

      if attributes.key?(:'last_kana')
        self.last_kana = attributes[:'last_kana']
      end

      if attributes.key?(:'post_code')
        self.post_code = attributes[:'post_code']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'fax_number')
        self.fax_number = attributes[:'fax_number']
      end

      if attributes.key?(:'mobile_number')
        self.mobile_number = attributes[:'mobile_number']
      end

      if attributes.key?(:'mail_address')
        self.mail_address = attributes[:'mail_address']
      end

      if attributes.key?(:'mail_address2')
        self.mail_address2 = attributes[:'mail_address2']
      end

      if attributes.key?(:'mail_address3')
        self.mail_address3 = attributes[:'mail_address3']
      end

      if attributes.key?(:'company_name')
        self.company_name = attributes[:'company_name']
      end

      if attributes.key?(:'department_name')
        self.department_name = attributes[:'department_name']
      end

      if attributes.key?(:'managerial_position')
        self.managerial_position = attributes[:'managerial_position']
      end

      if attributes.key?(:'sex')
        self.sex = attributes[:'sex']
      else
        self.sex = '0'
      end

      if attributes.key?(:'birth_date')
        self.birth_date = attributes[:'birth_date']
      end

      if attributes.key?(:'point_expire_date')
        self.point_expire_date = attributes[:'point_expire_date']
      end

      if attributes.key?(:'last_come_date_time')
        self.last_come_date_time = attributes[:'last_come_date_time']
      end

      if attributes.key?(:'entry_date')
        self.entry_date = attributes[:'entry_date']
      end

      if attributes.key?(:'leave_date')
        self.leave_date = attributes[:'leave_date']
      end

      if attributes.key?(:'point_giving_unit_price')
        self.point_giving_unit_price = attributes[:'point_giving_unit_price']
      end

      if attributes.key?(:'point_giving_unit')
        self.point_giving_unit = attributes[:'point_giving_unit']
      end

      if attributes.key?(:'pin_code')
        self.pin_code = attributes[:'pin_code']
      end

      if attributes.key?(:'passport_no')
        self.passport_no = attributes[:'passport_no']
      end

      if attributes.key?(:'nationality')
        self.nationality = attributes[:'nationality']
      end

      if attributes.key?(:'alphabet_name')
        self.alphabet_name = attributes[:'alphabet_name']
      end

      if attributes.key?(:'mail_receive_flag')
        self.mail_receive_flag = attributes[:'mail_receive_flag']
      else
        self.mail_receive_flag = '1'
      end

      if attributes.key?(:'note')
        self.note = attributes[:'note']
      end

      if attributes.key?(:'note2')
        self.note2 = attributes[:'note2']
      end

      if attributes.key?(:'favorite_list')
        self.favorite_list = attributes[:'favorite_list']
      end

      if attributes.key?(:'browsing_list')
        self.browsing_list = attributes[:'browsing_list']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'store_id')
        self.store_id = attributes[:'store_id']
      end

      if attributes.key?(:'ins_date_time')
        self.ins_date_time = attributes[:'ins_date_time']
      end

      if attributes.key?(:'upd_date_time')
        self.upd_date_time = attributes[:'upd_date_time']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @customer_id.nil?
        invalid_properties.push('invalid value for "customer_id", customer_id cannot be nil.')
      end

      if !@customer_code.nil? && @customer_code.to_s.length < 1
        invalid_properties.push('invalid value for "customer_code", the character length must be great than or equal to 1.')
      end

      if !@customer_no.nil? && @customer_no.to_s.length < 1
        invalid_properties.push('invalid value for "customer_no", the character length must be great than or equal to 1.')
      end

      if !@rank.nil? && @rank.to_s.length < 1
        invalid_properties.push('invalid value for "rank", the character length must be great than or equal to 1.')
      end

      if !@staff_rank.nil? && @staff_rank.to_s.length < 1
        invalid_properties.push('invalid value for "staff_rank", the character length must be great than or equal to 1.')
      end

      if !@first_name.nil? && @first_name.to_s.length < 1
        invalid_properties.push('invalid value for "first_name", the character length must be great than or equal to 1.')
      end

      if !@last_name.nil? && @last_name.to_s.length < 1
        invalid_properties.push('invalid value for "last_name", the character length must be great than or equal to 1.')
      end

      if !@first_kana.nil? && @first_kana.to_s.length < 1
        invalid_properties.push('invalid value for "first_kana", the character length must be great than or equal to 1.')
      end

      if !@last_kana.nil? && @last_kana.to_s.length < 1
        invalid_properties.push('invalid value for "last_kana", the character length must be great than or equal to 1.')
      end

      if !@post_code.nil? && @post_code.to_s.length < 1
        invalid_properties.push('invalid value for "post_code", the character length must be great than or equal to 1.')
      end

      if !@address.nil? && @address.to_s.length < 1
        invalid_properties.push('invalid value for "address", the character length must be great than or equal to 1.')
      end

      if !@phone_number.nil? && @phone_number.to_s.length < 1
        invalid_properties.push('invalid value for "phone_number", the character length must be great than or equal to 1.')
      end

      if !@fax_number.nil? && @fax_number.to_s.length < 1
        invalid_properties.push('invalid value for "fax_number", the character length must be great than or equal to 1.')
      end

      if !@mobile_number.nil? && @mobile_number.to_s.length < 1
        invalid_properties.push('invalid value for "mobile_number", the character length must be great than or equal to 1.')
      end

      if !@mail_address.nil? && @mail_address.to_s.length < 1
        invalid_properties.push('invalid value for "mail_address", the character length must be great than or equal to 1.')
      end

      if !@mail_address2.nil? && @mail_address2.to_s.length < 1
        invalid_properties.push('invalid value for "mail_address2", the character length must be great than or equal to 1.')
      end

      if !@mail_address3.nil? && @mail_address3.to_s.length < 1
        invalid_properties.push('invalid value for "mail_address3", the character length must be great than or equal to 1.')
      end

      if !@company_name.nil? && @company_name.to_s.length < 1
        invalid_properties.push('invalid value for "company_name", the character length must be great than or equal to 1.')
      end

      if !@department_name.nil? && @department_name.to_s.length < 1
        invalid_properties.push('invalid value for "department_name", the character length must be great than or equal to 1.')
      end

      if !@managerial_position.nil? && @managerial_position.to_s.length < 1
        invalid_properties.push('invalid value for "managerial_position", the character length must be great than or equal to 1.')
      end

      if !@birth_date.nil? && @birth_date.to_s.length < 1
        invalid_properties.push('invalid value for "birth_date", the character length must be great than or equal to 1.')
      end

      if !@point_expire_date.nil? && @point_expire_date.to_s.length < 1
        invalid_properties.push('invalid value for "point_expire_date", the character length must be great than or equal to 1.')
      end

      if !@last_come_date_time.nil? && @last_come_date_time.to_s.length < 1
        invalid_properties.push('invalid value for "last_come_date_time", the character length must be great than or equal to 1.')
      end

      if !@entry_date.nil? && @entry_date.to_s.length < 1
        invalid_properties.push('invalid value for "entry_date", the character length must be great than or equal to 1.')
      end

      if !@leave_date.nil? && @leave_date.to_s.length < 1
        invalid_properties.push('invalid value for "leave_date", the character length must be great than or equal to 1.')
      end

      if !@point_giving_unit_price.nil? && @point_giving_unit_price.to_s.length < 1
        invalid_properties.push('invalid value for "point_giving_unit_price", the character length must be great than or equal to 1.')
      end

      if !@point_giving_unit.nil? && @point_giving_unit.to_s.length < 1
        invalid_properties.push('invalid value for "point_giving_unit", the character length must be great than or equal to 1.')
      end

      if !@pin_code.nil? && @pin_code.to_s.length < 1
        invalid_properties.push('invalid value for "pin_code", the character length must be great than or equal to 1.')
      end

      if !@passport_no.nil? && @passport_no.to_s.length < 1
        invalid_properties.push('invalid value for "passport_no", the character length must be great than or equal to 1.')
      end

      if !@nationality.nil? && @nationality.to_s.length < 1
        invalid_properties.push('invalid value for "nationality", the character length must be great than or equal to 1.')
      end

      if !@alphabet_name.nil? && @alphabet_name.to_s.length < 1
        invalid_properties.push('invalid value for "alphabet_name", the character length must be great than or equal to 1.')
      end

      if !@note.nil? && @note.to_s.length < 1
        invalid_properties.push('invalid value for "note", the character length must be great than or equal to 1.')
      end

      if !@note2.nil? && @note2.to_s.length < 1
        invalid_properties.push('invalid value for "note2", the character length must be great than or equal to 1.')
      end

      if !@favorite_list.nil? && @favorite_list.to_s.length < 1
        invalid_properties.push('invalid value for "favorite_list", the character length must be great than or equal to 1.')
      end

      if !@browsing_list.nil? && @browsing_list.to_s.length < 1
        invalid_properties.push('invalid value for "browsing_list", the character length must be great than or equal to 1.')
      end

      if !@store_id.nil? && @store_id.to_s.length < 1
        invalid_properties.push('invalid value for "store_id", the character length must be great than or equal to 1.')
      end

      if !@ins_date_time.nil? && @ins_date_time.to_s.length < 1
        invalid_properties.push('invalid value for "ins_date_time", the character length must be great than or equal to 1.')
      end

      if !@upd_date_time.nil? && @upd_date_time.to_s.length < 1
        invalid_properties.push('invalid value for "upd_date_time", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @customer_id.nil?
      return false if !@customer_code.nil? && @customer_code.to_s.length < 1
      return false if !@customer_no.nil? && @customer_no.to_s.length < 1
      return false if !@rank.nil? && @rank.to_s.length < 1
      return false if !@staff_rank.nil? && @staff_rank.to_s.length < 1
      return false if !@first_name.nil? && @first_name.to_s.length < 1
      return false if !@last_name.nil? && @last_name.to_s.length < 1
      return false if !@first_kana.nil? && @first_kana.to_s.length < 1
      return false if !@last_kana.nil? && @last_kana.to_s.length < 1
      return false if !@post_code.nil? && @post_code.to_s.length < 1
      return false if !@address.nil? && @address.to_s.length < 1
      return false if !@phone_number.nil? && @phone_number.to_s.length < 1
      return false if !@fax_number.nil? && @fax_number.to_s.length < 1
      return false if !@mobile_number.nil? && @mobile_number.to_s.length < 1
      return false if !@mail_address.nil? && @mail_address.to_s.length < 1
      return false if !@mail_address2.nil? && @mail_address2.to_s.length < 1
      return false if !@mail_address3.nil? && @mail_address3.to_s.length < 1
      return false if !@company_name.nil? && @company_name.to_s.length < 1
      return false if !@department_name.nil? && @department_name.to_s.length < 1
      return false if !@managerial_position.nil? && @managerial_position.to_s.length < 1
      return false if !@birth_date.nil? && @birth_date.to_s.length < 1
      return false if !@point_expire_date.nil? && @point_expire_date.to_s.length < 1
      return false if !@last_come_date_time.nil? && @last_come_date_time.to_s.length < 1
      return false if !@entry_date.nil? && @entry_date.to_s.length < 1
      return false if !@leave_date.nil? && @leave_date.to_s.length < 1
      return false if !@point_giving_unit_price.nil? && @point_giving_unit_price.to_s.length < 1
      return false if !@point_giving_unit.nil? && @point_giving_unit.to_s.length < 1
      return false if !@pin_code.nil? && @pin_code.to_s.length < 1
      return false if !@passport_no.nil? && @passport_no.to_s.length < 1
      return false if !@nationality.nil? && @nationality.to_s.length < 1
      return false if !@alphabet_name.nil? && @alphabet_name.to_s.length < 1
      return false if !@note.nil? && @note.to_s.length < 1
      return false if !@note2.nil? && @note2.to_s.length < 1
      return false if !@favorite_list.nil? && @favorite_list.to_s.length < 1
      return false if !@browsing_list.nil? && @browsing_list.to_s.length < 1
      return false if !@store_id.nil? && @store_id.to_s.length < 1
      return false if !@ins_date_time.nil? && @ins_date_time.to_s.length < 1
      return false if !@upd_date_time.nil? && @upd_date_time.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_id Value to be assigned
    def customer_id=(customer_id)
      if customer_id.nil?
        fail ArgumentError, 'customer_id cannot be nil'
      end

      @customer_id = customer_id
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_code Value to be assigned
    def customer_code=(customer_code)
      if !customer_code.nil? && customer_code.to_s.length < 1
        fail ArgumentError, 'invalid value for "customer_code", the character length must be great than or equal to 1.'
      end

      @customer_code = customer_code
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_no Value to be assigned
    def customer_no=(customer_no)
      if !customer_no.nil? && customer_no.to_s.length < 1
        fail ArgumentError, 'invalid value for "customer_no", the character length must be great than or equal to 1.'
      end

      @customer_no = customer_no
    end

    # Custom attribute writer method with validation
    # @param [Object] rank Value to be assigned
    def rank=(rank)
      if !rank.nil? && rank.to_s.length < 1
        fail ArgumentError, 'invalid value for "rank", the character length must be great than or equal to 1.'
      end

      @rank = rank
    end

    # Custom attribute writer method with validation
    # @param [Object] staff_rank Value to be assigned
    def staff_rank=(staff_rank)
      if !staff_rank.nil? && staff_rank.to_s.length < 1
        fail ArgumentError, 'invalid value for "staff_rank", the character length must be great than or equal to 1.'
      end

      @staff_rank = staff_rank
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      if !first_name.nil? && first_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "first_name", the character length must be great than or equal to 1.'
      end

      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      if !last_name.nil? && last_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "last_name", the character length must be great than or equal to 1.'
      end

      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] first_kana Value to be assigned
    def first_kana=(first_kana)
      if !first_kana.nil? && first_kana.to_s.length < 1
        fail ArgumentError, 'invalid value for "first_kana", the character length must be great than or equal to 1.'
      end

      @first_kana = first_kana
    end

    # Custom attribute writer method with validation
    # @param [Object] last_kana Value to be assigned
    def last_kana=(last_kana)
      if !last_kana.nil? && last_kana.to_s.length < 1
        fail ArgumentError, 'invalid value for "last_kana", the character length must be great than or equal to 1.'
      end

      @last_kana = last_kana
    end

    # Custom attribute writer method with validation
    # @param [Object] post_code Value to be assigned
    def post_code=(post_code)
      if !post_code.nil? && post_code.to_s.length < 1
        fail ArgumentError, 'invalid value for "post_code", the character length must be great than or equal to 1.'
      end

      @post_code = post_code
    end

    # Custom attribute writer method with validation
    # @param [Object] address Value to be assigned
    def address=(address)
      if !address.nil? && address.to_s.length < 1
        fail ArgumentError, 'invalid value for "address", the character length must be great than or equal to 1.'
      end

      @address = address
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number Value to be assigned
    def phone_number=(phone_number)
      if !phone_number.nil? && phone_number.to_s.length < 1
        fail ArgumentError, 'invalid value for "phone_number", the character length must be great than or equal to 1.'
      end

      @phone_number = phone_number
    end

    # Custom attribute writer method with validation
    # @param [Object] fax_number Value to be assigned
    def fax_number=(fax_number)
      if !fax_number.nil? && fax_number.to_s.length < 1
        fail ArgumentError, 'invalid value for "fax_number", the character length must be great than or equal to 1.'
      end

      @fax_number = fax_number
    end

    # Custom attribute writer method with validation
    # @param [Object] mobile_number Value to be assigned
    def mobile_number=(mobile_number)
      if !mobile_number.nil? && mobile_number.to_s.length < 1
        fail ArgumentError, 'invalid value for "mobile_number", the character length must be great than or equal to 1.'
      end

      @mobile_number = mobile_number
    end

    # Custom attribute writer method with validation
    # @param [Object] mail_address Value to be assigned
    def mail_address=(mail_address)
      if !mail_address.nil? && mail_address.to_s.length < 1
        fail ArgumentError, 'invalid value for "mail_address", the character length must be great than or equal to 1.'
      end

      @mail_address = mail_address
    end

    # Custom attribute writer method with validation
    # @param [Object] mail_address2 Value to be assigned
    def mail_address2=(mail_address2)
      if !mail_address2.nil? && mail_address2.to_s.length < 1
        fail ArgumentError, 'invalid value for "mail_address2", the character length must be great than or equal to 1.'
      end

      @mail_address2 = mail_address2
    end

    # Custom attribute writer method with validation
    # @param [Object] mail_address3 Value to be assigned
    def mail_address3=(mail_address3)
      if !mail_address3.nil? && mail_address3.to_s.length < 1
        fail ArgumentError, 'invalid value for "mail_address3", the character length must be great than or equal to 1.'
      end

      @mail_address3 = mail_address3
    end

    # Custom attribute writer method with validation
    # @param [Object] company_name Value to be assigned
    def company_name=(company_name)
      if !company_name.nil? && company_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "company_name", the character length must be great than or equal to 1.'
      end

      @company_name = company_name
    end

    # Custom attribute writer method with validation
    # @param [Object] department_name Value to be assigned
    def department_name=(department_name)
      if !department_name.nil? && department_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "department_name", the character length must be great than or equal to 1.'
      end

      @department_name = department_name
    end

    # Custom attribute writer method with validation
    # @param [Object] managerial_position Value to be assigned
    def managerial_position=(managerial_position)
      if !managerial_position.nil? && managerial_position.to_s.length < 1
        fail ArgumentError, 'invalid value for "managerial_position", the character length must be great than or equal to 1.'
      end

      @managerial_position = managerial_position
    end

    # Custom attribute writer method with validation
    # @param [Object] birth_date Value to be assigned
    def birth_date=(birth_date)
      if !birth_date.nil? && birth_date.to_s.length < 1
        fail ArgumentError, 'invalid value for "birth_date", the character length must be great than or equal to 1.'
      end

      @birth_date = birth_date
    end

    # Custom attribute writer method with validation
    # @param [Object] point_expire_date Value to be assigned
    def point_expire_date=(point_expire_date)
      if !point_expire_date.nil? && point_expire_date.to_s.length < 1
        fail ArgumentError, 'invalid value for "point_expire_date", the character length must be great than or equal to 1.'
      end

      @point_expire_date = point_expire_date
    end

    # Custom attribute writer method with validation
    # @param [Object] last_come_date_time Value to be assigned
    def last_come_date_time=(last_come_date_time)
      if !last_come_date_time.nil? && last_come_date_time.to_s.length < 1
        fail ArgumentError, 'invalid value for "last_come_date_time", the character length must be great than or equal to 1.'
      end

      @last_come_date_time = last_come_date_time
    end

    # Custom attribute writer method with validation
    # @param [Object] entry_date Value to be assigned
    def entry_date=(entry_date)
      if !entry_date.nil? && entry_date.to_s.length < 1
        fail ArgumentError, 'invalid value for "entry_date", the character length must be great than or equal to 1.'
      end

      @entry_date = entry_date
    end

    # Custom attribute writer method with validation
    # @param [Object] leave_date Value to be assigned
    def leave_date=(leave_date)
      if !leave_date.nil? && leave_date.to_s.length < 1
        fail ArgumentError, 'invalid value for "leave_date", the character length must be great than or equal to 1.'
      end

      @leave_date = leave_date
    end

    # Custom attribute writer method with validation
    # @param [Object] point_giving_unit_price Value to be assigned
    def point_giving_unit_price=(point_giving_unit_price)
      if !point_giving_unit_price.nil? && point_giving_unit_price.to_s.length < 1
        fail ArgumentError, 'invalid value for "point_giving_unit_price", the character length must be great than or equal to 1.'
      end

      @point_giving_unit_price = point_giving_unit_price
    end

    # Custom attribute writer method with validation
    # @param [Object] point_giving_unit Value to be assigned
    def point_giving_unit=(point_giving_unit)
      if !point_giving_unit.nil? && point_giving_unit.to_s.length < 1
        fail ArgumentError, 'invalid value for "point_giving_unit", the character length must be great than or equal to 1.'
      end

      @point_giving_unit = point_giving_unit
    end

    # Custom attribute writer method with validation
    # @param [Object] pin_code Value to be assigned
    def pin_code=(pin_code)
      if !pin_code.nil? && pin_code.to_s.length < 1
        fail ArgumentError, 'invalid value for "pin_code", the character length must be great than or equal to 1.'
      end

      @pin_code = pin_code
    end

    # Custom attribute writer method with validation
    # @param [Object] passport_no Value to be assigned
    def passport_no=(passport_no)
      if !passport_no.nil? && passport_no.to_s.length < 1
        fail ArgumentError, 'invalid value for "passport_no", the character length must be great than or equal to 1.'
      end

      @passport_no = passport_no
    end

    # Custom attribute writer method with validation
    # @param [Object] nationality Value to be assigned
    def nationality=(nationality)
      if !nationality.nil? && nationality.to_s.length < 1
        fail ArgumentError, 'invalid value for "nationality", the character length must be great than or equal to 1.'
      end

      @nationality = nationality
    end

    # Custom attribute writer method with validation
    # @param [Object] alphabet_name Value to be assigned
    def alphabet_name=(alphabet_name)
      if !alphabet_name.nil? && alphabet_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "alphabet_name", the character length must be great than or equal to 1.'
      end

      @alphabet_name = alphabet_name
    end

    # Custom attribute writer method with validation
    # @param [Object] note Value to be assigned
    def note=(note)
      if !note.nil? && note.to_s.length < 1
        fail ArgumentError, 'invalid value for "note", the character length must be great than or equal to 1.'
      end

      @note = note
    end

    # Custom attribute writer method with validation
    # @param [Object] note2 Value to be assigned
    def note2=(note2)
      if !note2.nil? && note2.to_s.length < 1
        fail ArgumentError, 'invalid value for "note2", the character length must be great than or equal to 1.'
      end

      @note2 = note2
    end

    # Custom attribute writer method with validation
    # @param [Object] favorite_list Value to be assigned
    def favorite_list=(favorite_list)
      if !favorite_list.nil? && favorite_list.to_s.length < 1
        fail ArgumentError, 'invalid value for "favorite_list", the character length must be great than or equal to 1.'
      end

      @favorite_list = favorite_list
    end

    # Custom attribute writer method with validation
    # @param [Object] browsing_list Value to be assigned
    def browsing_list=(browsing_list)
      if !browsing_list.nil? && browsing_list.to_s.length < 1
        fail ArgumentError, 'invalid value for "browsing_list", the character length must be great than or equal to 1.'
      end

      @browsing_list = browsing_list
    end

    # Custom attribute writer method with validation
    # @param [Object] store_id Value to be assigned
    def store_id=(store_id)
      if !store_id.nil? && store_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "store_id", the character length must be great than or equal to 1.'
      end

      @store_id = store_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ins_date_time Value to be assigned
    def ins_date_time=(ins_date_time)
      if !ins_date_time.nil? && ins_date_time.to_s.length < 1
        fail ArgumentError, 'invalid value for "ins_date_time", the character length must be great than or equal to 1.'
      end

      @ins_date_time = ins_date_time
    end

    # Custom attribute writer method with validation
    # @param [Object] upd_date_time Value to be assigned
    def upd_date_time=(upd_date_time)
      if !upd_date_time.nil? && upd_date_time.to_s.length < 1
        fail ArgumentError, 'invalid value for "upd_date_time", the character length must be great than or equal to 1.'
      end

      @upd_date_time = upd_date_time
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          customer_id == o.customer_id &&
          customer_code == o.customer_code &&
          customer_no == o.customer_no &&
          rank == o.rank &&
          staff_rank == o.staff_rank &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          first_kana == o.first_kana &&
          last_kana == o.last_kana &&
          post_code == o.post_code &&
          address == o.address &&
          phone_number == o.phone_number &&
          fax_number == o.fax_number &&
          mobile_number == o.mobile_number &&
          mail_address == o.mail_address &&
          mail_address2 == o.mail_address2 &&
          mail_address3 == o.mail_address3 &&
          company_name == o.company_name &&
          department_name == o.department_name &&
          managerial_position == o.managerial_position &&
          sex == o.sex &&
          birth_date == o.birth_date &&
          point_expire_date == o.point_expire_date &&
          last_come_date_time == o.last_come_date_time &&
          entry_date == o.entry_date &&
          leave_date == o.leave_date &&
          point_giving_unit_price == o.point_giving_unit_price &&
          point_giving_unit == o.point_giving_unit &&
          pin_code == o.pin_code &&
          passport_no == o.passport_no &&
          nationality == o.nationality &&
          alphabet_name == o.alphabet_name &&
          mail_receive_flag == o.mail_receive_flag &&
          note == o.note &&
          note2 == o.note2 &&
          favorite_list == o.favorite_list &&
          browsing_list == o.browsing_list &&
          status == o.status &&
          store_id == o.store_id &&
          ins_date_time == o.ins_date_time &&
          upd_date_time == o.upd_date_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [customer_id, customer_code, customer_no, rank, staff_rank, first_name, last_name, first_kana, last_kana, post_code, address, phone_number, fax_number, mobile_number, mail_address, mail_address2, mail_address3, company_name, department_name, managerial_position, sex, birth_date, point_expire_date, last_come_date_time, entry_date, leave_date, point_giving_unit_price, point_giving_unit, pin_code, passport_no, nationality, alphabet_name, mail_receive_flag, note, note2, favorite_list, browsing_list, status, store_id, ins_date_time, upd_date_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
