=begin
#スマレジ

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PointUseDivision
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PointUseDivision do
  let(:instance) { OpenapiClient::PointUseDivision.new }

  describe 'test an instance of PointUseDivision' do
    it 'should create an instance of PointUseDivision' do
      expect(instance).to be_instance_of(OpenapiClient::PointUseDivision)
    end
  end
end
