<?php
/**
 * ExpireDivision
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ExpireDivision Class Doc Comment
 *
 * @category Class
 * @description ポイント失効期限の単位を設定 (0：なし、1：日、2：月、3：年) ポイント機能を使用しない場合は0 ポイント失効期限を指定する場合、0(なし)を指定するとエラー
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExpireDivision
{
    /**
     * Possible values of this enum
     */
    const NotExpired = '0';
    const ExpiredByDay = '1';
    const ExpiredByMonth = '2';
    const ExpiredByYear = '3';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NotExpired,
            self::ExpiredByDay,
            self::ExpiredByMonth,
            self::ExpiredByYear,
        ];
    }
}


