<?php
/**
 * Sort
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Sort Class Doc Comment
 *
 * @category Class
 * @description パラメータ名指定 カンマ区切り複数指定可、並び替え順指定「パラメータ名:desc」での指定が可能
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Sort
{
    /**
     * Possible values of this enum
     */
    const PRODUCT_CODEDESC = 'productCode:desc';
    const PRODUCT_CODEASC = 'productCode:asc';
    const TRANSACTION_DATE_TIMEDESC = 'transactionDateTime:desc';
    const TRANSACTION_DATE_TIMEASC = 'transactionDateTime:asc';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRODUCT_CODEDESC,
            self::PRODUCT_CODEASC,
            self::TRANSACTION_DATE_TIMEDESC,
            self::TRANSACTION_DATE_TIMEASC,
        ];
    }
}


