/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Coupon {
    #[serde(rename = "couponId")]
    pub coupon_id: String,
    #[serde(rename = "couponName", skip_serializing_if = "Option::is_none")]
    pub coupon_name: Option<String>,
    #[serde(rename = "couponDivision", skip_serializing_if = "Option::is_none")]
    pub coupon_division: Option<crate::models::CouponDivision>,
    #[serde(rename = "serialNumber")]
    pub serial_number: String,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "awardType", skip_serializing_if = "Option::is_none")]
    pub award_type: Option<crate::models::AwardType>,
    #[serde(rename = "awardValue", skip_serializing_if = "Option::is_none")]
    pub award_value: Option<String>,
    #[serde(rename = "applyConditionDivision", skip_serializing_if = "Option::is_none")]
    pub apply_condition_division: Option<crate::models::ApplyConditionDivision>,
    #[serde(rename = "minTargetPrice", skip_serializing_if = "Option::is_none")]
    pub min_target_price: Option<String>,
    #[serde(rename = "maxTargetPrice", skip_serializing_if = "Option::is_none")]
    pub max_target_price: Option<String>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "insDateTime", skip_serializing_if = "Option::is_none")]
    pub ins_date_time: Option<String>,
    #[serde(rename = "updDateTime", skip_serializing_if = "Option::is_none")]
    pub upd_date_time: Option<String>,
}

impl Coupon {
    pub fn new(coupon_id: String, serial_number: String) -> Coupon {
        Coupon {
            coupon_id,
            coupon_name: None,
            coupon_division: None,
            serial_number,
            summary: None,
            award_type: None,
            award_value: None,
            apply_condition_division: None,
            min_target_price: None,
            max_target_price: None,
            start_date: None,
            end_date: None,
            ins_date_time: None,
            upd_date_time: None,
        }
    }
}


