/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExpireDivision : ポイント失効期限の単位を設定 (0：なし、1：日、2：月、3：年) ポイント機能を使用しない場合は0 ポイント失効期限を指定する場合、0(なし)を指定するとエラー

/// ポイント失効期限の単位を設定 (0：なし、1：日、2：月、3：年) ポイント機能を使用しない場合は0 ポイント失効期限を指定する場合、0(なし)を指定するとエラー
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExpireDivision {
    #[serde(rename = "0")]
    NotExpired,
    #[serde(rename = "1")]
    ExpiredByDay,
    #[serde(rename = "2")]
    ExpiredByMonth,
    #[serde(rename = "3")]
    ExpiredByYear,

}

impl ToString for ExpireDivision {
    fn to_string(&self) -> String {
        match self {
            Self::NotExpired => String::from("0"),
            Self::ExpiredByDay => String::from("1"),
            Self::ExpiredByMonth => String::from("2"),
            Self::ExpiredByYear => String::from("3"),
        }
    }
}




