/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomersItem {
    #[serde(rename = "customerId")]
    pub customer_id: String,
    #[serde(rename = "customerCode")]
    pub customer_code: String,
    #[serde(rename = "customerNo", skip_serializing_if = "Option::is_none")]
    pub customer_no: Option<serde_json::Value>,
    #[serde(rename = "rank", skip_serializing_if = "Option::is_none")]
    pub rank: Option<serde_json::Value>,
    #[serde(rename = "staffRank", skip_serializing_if = "Option::is_none")]
    pub staff_rank: Option<serde_json::Value>,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "firstKana", skip_serializing_if = "Option::is_none")]
    pub first_kana: Option<serde_json::Value>,
    #[serde(rename = "lastKana", skip_serializing_if = "Option::is_none")]
    pub last_kana: Option<serde_json::Value>,
    #[serde(rename = "postCode", skip_serializing_if = "Option::is_none")]
    pub post_code: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "faxNumber", skip_serializing_if = "Option::is_none")]
    pub fax_number: Option<serde_json::Value>,
    #[serde(rename = "mobileNumber", skip_serializing_if = "Option::is_none")]
    pub mobile_number: Option<String>,
    #[serde(rename = "mailAddress", skip_serializing_if = "Option::is_none")]
    pub mail_address: Option<String>,
    #[serde(rename = "mailAddress2", skip_serializing_if = "Option::is_none")]
    pub mail_address2: Option<String>,
    #[serde(rename = "mailAddress3", skip_serializing_if = "Option::is_none")]
    pub mail_address3: Option<String>,
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<serde_json::Value>,
    #[serde(rename = "departmentName", skip_serializing_if = "Option::is_none")]
    pub department_name: Option<serde_json::Value>,
    #[serde(rename = "managerialPosition", skip_serializing_if = "Option::is_none")]
    pub managerial_position: Option<serde_json::Value>,
    #[serde(rename = "sex")]
    pub sex: crate::models::Sex,
    #[serde(rename = "birthDate", skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<serde_json::Value>,
    #[serde(rename = "pointExpireDate", skip_serializing_if = "Option::is_none")]
    pub point_expire_date: Option<serde_json::Value>,
    #[serde(rename = "lastComeDateTime", skip_serializing_if = "Option::is_none")]
    pub last_come_date_time: Option<serde_json::Value>,
    #[serde(rename = "entryDate", skip_serializing_if = "Option::is_none")]
    pub entry_date: Option<serde_json::Value>,
    #[serde(rename = "leaveDate", skip_serializing_if = "Option::is_none")]
    pub leave_date: Option<String>,
    #[serde(rename = "pointGivingUnitPrice", skip_serializing_if = "Option::is_none")]
    pub point_giving_unit_price: Option<serde_json::Value>,
    #[serde(rename = "pointGivingUnit", skip_serializing_if = "Option::is_none")]
    pub point_giving_unit: Option<serde_json::Value>,
    #[serde(rename = "pinCode", skip_serializing_if = "Option::is_none")]
    pub pin_code: Option<serde_json::Value>,
    #[serde(rename = "passportNo", skip_serializing_if = "Option::is_none")]
    pub passport_no: Option<serde_json::Value>,
    #[serde(rename = "nationality", skip_serializing_if = "Option::is_none")]
    pub nationality: Option<serde_json::Value>,
    #[serde(rename = "alphabetName", skip_serializing_if = "Option::is_none")]
    pub alphabet_name: Option<serde_json::Value>,
    #[serde(rename = "mailReceiveFlag")]
    pub mail_receive_flag: crate::models::MailReceiveFlag,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<serde_json::Value>,
    #[serde(rename = "note2", skip_serializing_if = "Option::is_none")]
    pub note2: Option<serde_json::Value>,
    #[serde(rename = "favoriteList", skip_serializing_if = "Option::is_none")]
    pub favorite_list: Option<serde_json::Value>,
    #[serde(rename = "browsingList", skip_serializing_if = "Option::is_none")]
    pub browsing_list: Option<serde_json::Value>,
    #[serde(rename = "status")]
    pub status: crate::models::Status,
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<serde_json::Value>,
    #[serde(rename = "insDateTime")]
    pub ins_date_time: String,
    #[serde(rename = "updDateTime")]
    pub upd_date_time: String,
}

impl GetCustomersItem {
    pub fn new(customer_id: String, customer_code: String, sex: crate::models::Sex, mail_receive_flag: crate::models::MailReceiveFlag, status: crate::models::Status, ins_date_time: String, upd_date_time: String) -> GetCustomersItem {
        GetCustomersItem {
            customer_id,
            customer_code,
            customer_no: None,
            rank: None,
            staff_rank: None,
            first_name: None,
            last_name: None,
            first_kana: None,
            last_kana: None,
            post_code: None,
            address: None,
            phone_number: None,
            fax_number: None,
            mobile_number: None,
            mail_address: None,
            mail_address2: None,
            mail_address3: None,
            company_name: None,
            department_name: None,
            managerial_position: None,
            sex,
            birth_date: None,
            point_expire_date: None,
            last_come_date_time: None,
            entry_date: None,
            leave_date: None,
            point_giving_unit_price: None,
            point_giving_unit: None,
            pin_code: None,
            passport_no: None,
            nationality: None,
            alphabet_name: None,
            mail_receive_flag,
            note: None,
            note2: None,
            favorite_list: None,
            browsing_list: None,
            status,
            store_id: None,
            ins_date_time,
            upd_date_time,
        }
    }
}


