/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomerRequiredColumnSettingResponse {
    /// カラム名
    #[serde(rename = "columnName")]
    pub column_name: String,
    #[serde(rename = "value")]
    pub value: crate::models::CustomerRequiredColumnDivision,
}

impl GetCustomerRequiredColumnSettingResponse {
    pub fn new(column_name: String, value: crate::models::CustomerRequiredColumnDivision) -> GetCustomerRequiredColumnSettingResponse {
        GetCustomerRequiredColumnSettingResponse {
            column_name,
            value,
        }
    }
}


