/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PointUpdateDivision : 会員ポイントの更新フラグ。 0:（デフォルト値）：ポイント変動なし 1:変動あり（対象取引によって実際に加算・減算されたポイントの差分を、更新前のユーザーから更新後のユーザーに付け替える形で更新） 2:変動あり（更新前・更新後の会員それぞれに対して、現在の会員個人設定または会員ランク、店舗のポイント付与区分を対象取引の内容に照らして、再計算した当該取引におけるポイント差分を反映する形で更新）

/// 会員ポイントの更新フラグ。 0:（デフォルト値）：ポイント変動なし 1:変動あり（対象取引によって実際に加算・減算されたポイントの差分を、更新前のユーザーから更新後のユーザーに付け替える形で更新） 2:変動あり（更新前・更新後の会員それぞれに対して、現在の会員個人設定または会員ランク、店舗のポイント付与区分を対象取引の内容に照らして、再計算した当該取引におけるポイント差分を反映する形で更新）
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PointUpdateDivision {
    #[serde(rename = "0")]
    NotUpdated,
    #[serde(rename = "1")]
    MovePoint,
    #[serde(rename = "2")]
    RecalculatePoint,

}

impl ToString for PointUpdateDivision {
    fn to_string(&self) -> String {
        match self {
            Self::NotUpdated => String::from("0"),
            Self::MovePoint => String::from("1"),
            Self::RecalculatePoint => String::from("2"),
        }
    }
}




