/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionDetail {
    #[serde(rename = "transactionHeadId")]
    pub transaction_head_id: String,
    #[serde(rename = "transactionDetailId")]
    pub transaction_detail_id: String,
    #[serde(rename = "parentTransactionDetailId", skip_serializing_if = "Option::is_none")]
    pub parent_transaction_detail_id: Option<String>,
    #[serde(rename = "transactionDetailDivision")]
    pub transaction_detail_division: crate::models::TransactionDetailDivision,
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "productCode", skip_serializing_if = "Option::is_none")]
    pub product_code: Option<String>,
    #[serde(rename = "productName", skip_serializing_if = "Option::is_none")]
    pub product_name: Option<String>,
    #[serde(rename = "printReceiptProductName", skip_serializing_if = "Option::is_none")]
    pub print_receipt_product_name: Option<String>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    #[serde(rename = "groupCode", skip_serializing_if = "Option::is_none")]
    pub group_code: Option<String>,
    #[serde(rename = "taxDivision", skip_serializing_if = "Option::is_none")]
    pub tax_division: Option<crate::models::TaxDivision>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    #[serde(rename = "salesPrice", skip_serializing_if = "Option::is_none")]
    pub sales_price: Option<String>,
    #[serde(rename = "unitDiscountPrice", skip_serializing_if = "Option::is_none")]
    pub unit_discount_price: Option<String>,
    #[serde(rename = "unitDiscountRate", skip_serializing_if = "Option::is_none")]
    pub unit_discount_rate: Option<String>,
    #[serde(rename = "unitDiscountDivision", skip_serializing_if = "Option::is_none")]
    pub unit_discount_division: Option<String>,
    #[serde(rename = "cost", skip_serializing_if = "Option::is_none")]
    pub cost: Option<String>,
    #[serde(rename = "quantity")]
    pub quantity: String,
    #[serde(rename = "unitNonDiscountSum", skip_serializing_if = "Option::is_none")]
    pub unit_non_discount_sum: Option<String>,
    #[serde(rename = "unitDiscountSum", skip_serializing_if = "Option::is_none")]
    pub unit_discount_sum: Option<String>,
    #[serde(rename = "unitDiscountedSum", skip_serializing_if = "Option::is_none")]
    pub unit_discounted_sum: Option<String>,
    #[serde(rename = "costSum", skip_serializing_if = "Option::is_none")]
    pub cost_sum: Option<String>,
    #[serde(rename = "categoryId", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<String>,
    #[serde(rename = "categoryName", skip_serializing_if = "Option::is_none")]
    pub category_name: Option<String>,
    #[serde(rename = "discriminationNo", skip_serializing_if = "Option::is_none")]
    pub discrimination_no: Option<String>,
    #[serde(rename = "salesDivision", skip_serializing_if = "Option::is_none")]
    pub sales_division: Option<crate::models::SalesDivision>,
    #[serde(rename = "productDivision", skip_serializing_if = "Option::is_none")]
    pub product_division: Option<crate::models::ProductDivision>,
    #[serde(rename = "inventoryReservationDivision", skip_serializing_if = "Option::is_none")]
    pub inventory_reservation_division: Option<String>,
    #[serde(rename = "pointNotApplicable", skip_serializing_if = "Option::is_none")]
    pub point_not_applicable: Option<String>,
    #[serde(rename = "calcDiscount", skip_serializing_if = "Option::is_none")]
    pub calc_discount: Option<String>,
    #[serde(rename = "taxFreeDivision", skip_serializing_if = "Option::is_none")]
    pub tax_free_division: Option<String>,
    #[serde(rename = "taxFreeCommodityPrice", skip_serializing_if = "Option::is_none")]
    pub tax_free_commodity_price: Option<String>,
    #[serde(rename = "taxFree", skip_serializing_if = "Option::is_none")]
    pub tax_free: Option<String>,
    #[serde(rename = "productBundleGroupId", skip_serializing_if = "Option::is_none")]
    pub product_bundle_group_id: Option<String>,
    #[serde(rename = "discountPriceProportional", skip_serializing_if = "Option::is_none")]
    pub discount_price_proportional: Option<String>,
    #[serde(rename = "discountPointProportional", skip_serializing_if = "Option::is_none")]
    pub discount_point_proportional: Option<String>,
    #[serde(rename = "discountCouponProportional", skip_serializing_if = "Option::is_none")]
    pub discount_coupon_proportional: Option<String>,
    #[serde(rename = "taxIncludeProportional", skip_serializing_if = "Option::is_none")]
    pub tax_include_proportional: Option<String>,
    #[serde(rename = "taxExcludeProportional", skip_serializing_if = "Option::is_none")]
    pub tax_exclude_proportional: Option<String>,
    #[serde(rename = "productBundleProportional", skip_serializing_if = "Option::is_none")]
    pub product_bundle_proportional: Option<String>,
    #[serde(rename = "staffDiscountProportional", skip_serializing_if = "Option::is_none")]
    pub staff_discount_proportional: Option<String>,
    #[serde(rename = "bargainDiscountProportional", skip_serializing_if = "Option::is_none")]
    pub bargain_discount_proportional: Option<String>,
    #[serde(rename = "roundingPriceProportional", skip_serializing_if = "Option::is_none")]
    pub rounding_price_proportional: Option<String>,
    #[serde(rename = "productStaffDiscountRate", skip_serializing_if = "Option::is_none")]
    pub product_staff_discount_rate: Option<String>,
    #[serde(rename = "staffRank", skip_serializing_if = "Option::is_none")]
    pub staff_rank: Option<String>,
    #[serde(rename = "staffRankName", skip_serializing_if = "Option::is_none")]
    pub staff_rank_name: Option<String>,
    #[serde(rename = "staffDiscountRate", skip_serializing_if = "Option::is_none")]
    pub staff_discount_rate: Option<String>,
    #[serde(rename = "staffDiscountDivision", skip_serializing_if = "Option::is_none")]
    pub staff_discount_division: Option<String>,
    #[serde(rename = "applyStaffDiscountRate", skip_serializing_if = "Option::is_none")]
    pub apply_staff_discount_rate: Option<String>,
    #[serde(rename = "applyStaffDiscountPrice", skip_serializing_if = "Option::is_none")]
    pub apply_staff_discount_price: Option<String>,
    #[serde(rename = "bargainId", skip_serializing_if = "Option::is_none")]
    pub bargain_id: Option<String>,
    #[serde(rename = "bargainName", skip_serializing_if = "Option::is_none")]
    pub bargain_name: Option<String>,
    #[serde(rename = "bargainDivision", skip_serializing_if = "Option::is_none")]
    pub bargain_division: Option<String>,
    #[serde(rename = "bargainValue", skip_serializing_if = "Option::is_none")]
    pub bargain_value: Option<String>,
    #[serde(rename = "applyBargainValue", skip_serializing_if = "Option::is_none")]
    pub apply_bargain_value: Option<String>,
    #[serde(rename = "applyBargainDiscountPrice", skip_serializing_if = "Option::is_none")]
    pub apply_bargain_discount_price: Option<String>,
    #[serde(rename = "taxRate", skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<String>,
    #[serde(rename = "standardTaxRate", skip_serializing_if = "Option::is_none")]
    pub standard_tax_rate: Option<String>,
    #[serde(rename = "modifiedTaxRate", skip_serializing_if = "Option::is_none")]
    pub modified_tax_rate: Option<String>,
    #[serde(rename = "reduceTaxId", skip_serializing_if = "Option::is_none")]
    pub reduce_tax_id: Option<String>,
    #[serde(rename = "reduceTaxName", skip_serializing_if = "Option::is_none")]
    pub reduce_tax_name: Option<String>,
    #[serde(rename = "reduceTaxRate", skip_serializing_if = "Option::is_none")]
    pub reduce_tax_rate: Option<String>,
    #[serde(rename = "reduceTaxPrice", skip_serializing_if = "Option::is_none")]
    pub reduce_tax_price: Option<String>,
    #[serde(rename = "reduceTaxMemberPrice", skip_serializing_if = "Option::is_none")]
    pub reduce_tax_member_price: Option<String>,
}

impl TransactionDetail {
    pub fn new(transaction_head_id: String, transaction_detail_id: String, transaction_detail_division: crate::models::TransactionDetailDivision, quantity: String) -> TransactionDetail {
        TransactionDetail {
            transaction_head_id,
            transaction_detail_id,
            parent_transaction_detail_id: None,
            transaction_detail_division,
            product_id: None,
            product_code: None,
            product_name: None,
            print_receipt_product_name: None,
            color: None,
            size: None,
            group_code: None,
            tax_division: None,
            price: None,
            sales_price: None,
            unit_discount_price: None,
            unit_discount_rate: None,
            unit_discount_division: None,
            cost: None,
            quantity,
            unit_non_discount_sum: None,
            unit_discount_sum: None,
            unit_discounted_sum: None,
            cost_sum: None,
            category_id: None,
            category_name: None,
            discrimination_no: None,
            sales_division: None,
            product_division: None,
            inventory_reservation_division: None,
            point_not_applicable: None,
            calc_discount: None,
            tax_free_division: None,
            tax_free_commodity_price: None,
            tax_free: None,
            product_bundle_group_id: None,
            discount_price_proportional: None,
            discount_point_proportional: None,
            discount_coupon_proportional: None,
            tax_include_proportional: None,
            tax_exclude_proportional: None,
            product_bundle_proportional: None,
            staff_discount_proportional: None,
            bargain_discount_proportional: None,
            rounding_price_proportional: None,
            product_staff_discount_rate: None,
            staff_rank: None,
            staff_rank_name: None,
            staff_discount_rate: None,
            staff_discount_division: None,
            apply_staff_discount_rate: None,
            apply_staff_discount_price: None,
            bargain_id: None,
            bargain_name: None,
            bargain_division: None,
            bargain_value: None,
            apply_bargain_value: None,
            apply_bargain_discount_price: None,
            tax_rate: None,
            standard_tax_rate: None,
            modified_tax_rate: None,
            reduce_tax_id: None,
            reduce_tax_name: None,
            reduce_tax_rate: None,
            reduce_tax_price: None,
            reduce_tax_member_price: None,
        }
    }
}


