/*
 * スマレジ
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStoreResponse {
    #[serde(rename = "storeId")]
    pub store_id: String,
    #[serde(rename = "storeCode", skip_serializing_if = "Option::is_none")]
    pub store_code: Option<String>,
    #[serde(rename = "storeName", skip_serializing_if = "Option::is_none")]
    pub store_name: Option<String>,
    #[serde(rename = "storeAbbr", skip_serializing_if = "Option::is_none")]
    pub store_abbr: Option<String>,
    #[serde(rename = "printReceiptStoreName", skip_serializing_if = "Option::is_none")]
    pub print_receipt_store_name: Option<String>,
    #[serde(rename = "printStockReceiptStoreName", skip_serializing_if = "Option::is_none")]
    pub print_stock_receipt_store_name: Option<String>,
    #[serde(rename = "division")]
    pub division: crate::models::StoreDivision,
    #[serde(rename = "postCode", skip_serializing_if = "Option::is_none")]
    pub post_code: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "faxNumber", skip_serializing_if = "Option::is_none")]
    pub fax_number: Option<String>,
    #[serde(rename = "mailAddress", skip_serializing_if = "Option::is_none")]
    pub mail_address: Option<String>,
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    #[serde(rename = "tempTranMailAddress", skip_serializing_if = "Option::is_none")]
    pub temp_tran_mail_address: Option<String>,
    #[serde(rename = "priceChangeFlag", skip_serializing_if = "Option::is_none")]
    pub price_change_flag: Option<String>,
    #[serde(rename = "sellDivision", skip_serializing_if = "Option::is_none")]
    pub sell_division: Option<f32>,
    #[serde(rename = "sumProcDivision", skip_serializing_if = "Option::is_none")]
    pub sum_proc_division: Option<f32>,
    #[serde(rename = "sumDateChangeTime", skip_serializing_if = "Option::is_none")]
    pub sum_date_change_time: Option<String>,
    #[serde(rename = "sumRefColumn", skip_serializing_if = "Option::is_none")]
    pub sum_ref_column: Option<f32>,
    #[serde(rename = "pointNotApplicable", skip_serializing_if = "Option::is_none")]
    pub point_not_applicable: Option<f32>,
    #[serde(rename = "taxFreeDivision", skip_serializing_if = "Option::is_none")]
    pub tax_free_division: Option<f32>,
    #[serde(rename = "maxBundleProductCount", skip_serializing_if = "Option::is_none")]
    pub max_bundle_product_count: Option<String>,
    #[serde(rename = "maxDiscountRate", skip_serializing_if = "Option::is_none")]
    pub max_discount_rate: Option<String>,
    #[serde(rename = "carriageDisplayFlag", skip_serializing_if = "Option::is_none")]
    pub carriage_display_flag: Option<f32>,
    #[serde(rename = "terminalAdjustmentCashFlag", skip_serializing_if = "Option::is_none")]
    pub terminal_adjustment_cash_flag: Option<f32>,
    #[serde(rename = "terminalCheckCashFlag", skip_serializing_if = "Option::is_none")]
    pub terminal_check_cash_flag: Option<f32>,
    #[serde(rename = "waiterAdjustmentDivision", skip_serializing_if = "Option::is_none")]
    pub waiter_adjustment_division: Option<f32>,
    #[serde(rename = "savingAutoDivision", skip_serializing_if = "Option::is_none")]
    pub saving_auto_division: Option<f32>,
    #[serde(rename = "savingAutoPrice", skip_serializing_if = "Option::is_none")]
    pub saving_auto_price: Option<String>,
    #[serde(rename = "cancelSettingDivision", skip_serializing_if = "Option::is_none")]
    pub cancel_setting_division: Option<f32>,
    #[serde(rename = "roundingDivision", skip_serializing_if = "Option::is_none")]
    pub rounding_division: Option<String>,
    #[serde(rename = "discountRoundingDivision", skip_serializing_if = "Option::is_none")]
    pub discount_rounding_division: Option<f32>,
    #[serde(rename = "cardCompanySelectDivision", skip_serializing_if = "Option::is_none")]
    pub card_company_select_division: Option<f32>,
    #[serde(rename = "giftReceiptValidDays", skip_serializing_if = "Option::is_none")]
    pub gift_receipt_valid_days: Option<String>,
    #[serde(rename = "taxLabelNormal", skip_serializing_if = "Option::is_none")]
    pub tax_label_normal: Option<String>,
    #[serde(rename = "taxLabelReduce", skip_serializing_if = "Option::is_none")]
    pub tax_label_reduce: Option<String>,
    #[serde(rename = "displaySequence", skip_serializing_if = "Option::is_none")]
    pub display_sequence: Option<String>,
    #[serde(rename = "facePaymentUseDivision", skip_serializing_if = "Option::is_none")]
    pub face_payment_use_division: Option<String>,
    #[serde(rename = "insDateTime", skip_serializing_if = "Option::is_none")]
    pub ins_date_time: Option<String>,
    #[serde(rename = "updDateTime", skip_serializing_if = "Option::is_none")]
    pub upd_date_time: Option<String>,
    #[serde(rename = "pointCondition", skip_serializing_if = "Option::is_none")]
    pub point_condition: Option<Box<crate::models::PointCondition>>,
    #[serde(rename = "receiptPrintInfo", skip_serializing_if = "Option::is_none")]
    pub receipt_print_info: Option<Box<crate::models::UpdateStoreResponseReceiptPrintInfo>>,
}

impl UpdateStoreResponse {
    pub fn new(store_id: String, division: crate::models::StoreDivision) -> UpdateStoreResponse {
        UpdateStoreResponse {
            store_id,
            store_code: None,
            store_name: None,
            store_abbr: None,
            print_receipt_store_name: None,
            print_stock_receipt_store_name: None,
            division,
            post_code: None,
            address: None,
            phone_number: None,
            fax_number: None,
            mail_address: None,
            homepage: None,
            temp_tran_mail_address: None,
            price_change_flag: None,
            sell_division: None,
            sum_proc_division: None,
            sum_date_change_time: None,
            sum_ref_column: None,
            point_not_applicable: None,
            tax_free_division: None,
            max_bundle_product_count: None,
            max_discount_rate: None,
            carriage_display_flag: None,
            terminal_adjustment_cash_flag: None,
            terminal_check_cash_flag: None,
            waiter_adjustment_division: None,
            saving_auto_division: None,
            saving_auto_price: None,
            cancel_setting_division: None,
            rounding_division: None,
            discount_rounding_division: None,
            card_company_select_division: None,
            gift_receipt_valid_days: None,
            tax_label_normal: None,
            tax_label_reduce: None,
            display_sequence: None,
            face_payment_use_division: None,
            ins_date_time: None,
            upd_date_time: None,
            point_condition: None,
            receipt_print_info: None,
        }
    }
}


